sonar.projectKey=books-catalog
sonar.projectName=Books Catalog API
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,__tests__/**
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
